---
title: "data-preparation"
output: 
  html_document:
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r message=FALSE, warning=FALSE}
library(sf)
library(readr)
library(mapview)
library(tidyverse)
library(ggthemes)
library(webshot)
library(leaflet)
library(leafgl)
library(leaflet.extras)
library(htmlwidgets)
library(RColorBrewer)
library(here)
library(skimr)
library(janitor)
library(datapasta)
```

# Data
```{r message=FALSE, warning=FALSE, include=FALSE}
# geometries with 'U_ID' and 'source' (Cities and WMT)
sf <- st_read(here("2022/data/result_feb2021.gpkg"))
df <- read_csv(here("2022/data/result_feb2021 - Sheet1.csv"))
```

```{r}
df %>%
  select(132,5,17,73,25,27,57,59:62,64,69,133,134,135,141,142,136,137,138,139,140) %>%
  clean_names() %>%
  rename_with(~gsub("\\d+", "", .)) %>%
  rename_all(~str_replace_all(.,"x__","")) %>%
  rename(description_of_1 = "s_d_rs___description_of",
         category_plus = "cetegory_plus") %>%
  clean_names(case = "sentence") -> df1

# df %>%
#   count(`19_31_Floor_levels_t`) %>%
#   arrange(desc(n))

# edit values text cases.
df1 %>%
  mutate_at(c(2), str_to_title) %>%
  mutate_at(c(4), str_to_title) -> df1

# create new variable 'Level' to account for overlapping records
df1 %>%
  mutate(Level = case_when(str_detect(`Floor levels t`, "Ground") ~ "G",
                                      TRUE ~ "L1"),
         Level = case_when(is.na(`Floor levels t`) ~ "G",
                           TRUE ~ Level),
         Level = case_when(`Floor levels t` %in%  c("Level 2", "Level 3", "Level 4 and above") ~ "L2",
                           TRUE ~ Level)) -> df1

#write_csv(df1, here("2022/data/dataframe-clean-2022.csv"))
```

```{r}
sf %>%
  select(U_ID) %>%
  left_join(df1, by = c("U_ID" = "U id")) -> sf1

sf1 %>%
  filter(st_is_empty(.) == FALSE) -> sf1

# WMT building polygons
sfw <- st_read(here("f_wmt_poi_Buildings.gpkg"))
sfw %>%
  select(U_ID) -> sfw1

#st_write(sf1, here("2022/data/geoms-temp.gpkg"), append=FALSE)
```

```{r}
sf1 %>%
  mutate(geomtype = st_geometry_type(.)) -> sf2

# not wmt and NA
sf2 %>%
  filter(Source != "WMT" | is.na(Source)) -> sf2nw

# wmt
sf2 %>%
  filter(Source == "WMT") -> sf2w

# polygons
sf2w %>%
  filter(U_ID %in% sfw1$U_ID) %>%
  # sfw1 are polygons
  st_sf(geom = sfw1[sfw1$U_ID %in% sf2w$U_ID,]$geom) -> sf2wpol

# points
sf2w %>%
  filter(!U_ID %in% sf2wpol$U_ID) %>%
  st_buffer(4) -> sf2wpoi

# bind together (2277,545,223)
sf2nw %>%
  bind_rows(sf2wpoi) %>%
  bind_rows(sf2wpol) %>%
  st_cast("MULTIPOLYGON") -> geoms

# create simplified category.
sector <- data.frame(
  stringsAsFactors = FALSE,
     Category.plus = c("Vehicle / equipment depot, construction related",
                       "Vehicle / equipment depot, public transport",
                       "Vehicle / equipment depot, other inc service / hire","Vehicle / parts sale","Waste / recycling",
                       "Utilities infrastructure","Distribution / courier facility",
                       "Wholesale, food / drink",
                       "Wholesale, building materials / equipment in hire","Wholesale, other",
                       "Repair, motor vehicles","Repair, other",
                       "Manufacture of food / drink","Artisan / art production",
                       "Bespoke fabrication, construction","Bespoke fabrication, other","Printing",
                       "Laundry","Manufacture, other",
                       "Fully / predominantly housing","Housing within mixed development",
                       "Fully / predominantly non-industrial other than housing",
                       "Vacant industrial","Vacant, other than industrial","Demolished",
                       "Storage","Unknown"),
            Sector = c("Transportation and Storage",
                       "Transportation and Storage","Transportation and Storage",
                       "Retail Trade","Waste Management","Utilities supply",
                       "Transportation and Storage","Wholesale","Wholesale",
                       "Wholesale","Repair of Motor Vehicles","Manufacturing",
                       "Manufacturing","Manufacturing","Manufacturing",
                       "Manufacturing","Manufacturing","Other Service Activities",
                       "Manufacturing","n/a","n/a","n/a","Vacant Industrial",
                       "n/a","n/a","Transportation and Storage","n/a"))

# append sectors
geoms %>%
  left_join(., sector, by = c("Category plus" = "Category.plus")) -> geoms

geoms %>%
  select(-geomtype) -> geoms
```

```{r message=FALSE, warning=FALSE}
# calculate heading for gsv

streets <- st_read(here("2022/data/oproad_gbRoadLink.gpkg"))
geoms %>%
  st_centroid() -> cent

#remotes::install_github("michaeldorman/nngeo")
library(nngeo)
library(lwgeom)

st_connect(cent, streets) -> lines

# ref: https://stackoverflow.com/questions/72276233/calculate-the-angle-between-two-sf-points-in-r-to-calculate-the-direction-of-roa

lines %>%
  st_as_sf() %>%
  st_transform(4326) -> lines

lines %>%
  mutate(id = row.names(.)) %>%
  st_cast("POINT") %>% ## split into constituent points
  group_by(id) %>% 
  filter(row_number()==1 | row_number()==n()) %>% ## take start and end points of each osm id
  mutate(bearing = c(lwgeom::st_geod_azimuth(x))) %>% ## calculate bearing of start and end points
  mutate(bearing = as.numeric(units::set_units(bearing, "degrees"))) %>% ## convert to degrees
  distinct(id, .keep_all = TRUE) -> linesb ## just take one point for each id

# correct possible rotation?
linesb %>%
  mutate(bearing2 = case_when(bearing > 0 & bearing <= 90 ~ 90 - bearing,
                              bearing > 90 & bearing <= 180 ~ (180 - bearing) + 270,
                              bearing < 0 & bearing >= -90 ~ 90 + abs(bearing),
                              bearing < -90 & bearing >= -180 ~ 90 + abs(bearing))) %>%
  ungroup() %>%
  mutate(coordx = st_coordinates(.)[,1],
         coordy = st_coordinates(.)[,2],
         heading = bearing - 180) -> linesb1

# append new data
geoms %>%
  bind_cols(linesb1[,c("coordx", "coordy", "heading")]) %>%
  select(-x) -> geoms
```

```{r message=FALSE, warning=FALSE}
#mapview(linesb1) + mapview(lines)
```


51.4772738,-0.0952892

id=1695
https://maps.googleapis.com/maps/api/streetview?size=640x640&location=51.47701,-0.09523967&heading=180&pitch=1&key=AIzaSyC-v_x-RZvp_a545Q-XCRf_NGwEo9X7mBI&width=320

id=1345
51.47158,-0.06857268 9.2021635 (+90)
https://maps.googleapis.com/maps/api/streetview?size=640x640&location=51.47158,-0.06857268&heading=99&pitch=1&key=AIzaSyC-v_x-RZvp_a545Q-XCRf_NGwEo9X7mBI&width=320

id=551
51.47625,-0.05574886
https://maps.googleapis.com/maps/api/streetview?size=640x640&location=51.47625,-0.05574886&heading=-248.2&pitch=1&key=AIzaSyC-v_x-RZvp_a545Q-XCRf_NGwEo9X7mBI&width=320




```{r}
#st_write(geoms, here("2022/data/survey-results.gpkg"), append=FALSE)
#st_write(geoms, here("2022/data/survey-results.geojson"), append=FALSE)
#st_write(geoms, here("2022/data/survey-results.csv"), layer_options = c("GEOMETRY=AS_WKT","CREATE_CSVT=YES"), delete_dsn=TRUE)
```

```{r}
geom %>%
  st_drop_geometry() %>%
  count(Category.plus) %>%
  print.AsIs()
```

```{r}
geom %>%
  st_drop_geometry() %>%
  count(Category.plus) %>%
  arrange(desc(n)) %>%
  print.AsIs()
```


```{r}
skim(geoms) -> table
table
table %>%
  select(skim_variable, n_missing, complete_rate) %>%
  arrange(desc(complete_rate))
```

```{r}
writexl::write_xlsx(table, here("2022/data/data-completeness-report.xlsx"))
```

