---
title: "Leaflet webapp"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r message=FALSE, warning=FALSE}
library(sf)
library(readr)
library(mapview)
library(tidyverse)
library(ggthemes)
library(webshot)
library(leaflet)
library(leafgl)
library(leaflet.extras)
library(htmlwidgets)
library(RColorBrewer)
library(here)
library(skimr)
library(janitor)
```

# Data
```{r message=FALSE, warning=FALSE, include=FALSE}
# geometries with 'U_ID' and 'source' (Cities and WMT)
sf <- st_read(here("2022/data/result_feb2021.gpkg"))
df <- read_csv(here("2022/data/result_feb2021 - Sheet1.csv"))
```


```{r}
names(df)
```


```{r}
df %>%
  select(132,5,17,73,25,27,57,59:62,64,69,133,134,135,141,142,136,137,138,139,140) %>%
  clean_names() %>%
  rename_with(~gsub("\\d+", "", .)) %>%
  rename_all(~str_replace_all(.,"x__","")) %>%
  rename(description_of_1 = "s_d_rs___description_of",
         category_plus = "cetegory_plus") %>%
  clean_names(case = "sentence") -> df1

# edit values text cases.
df1 %>%
  mutate_at(c(2), str_to_title) %>%
  mutate_at(c(4), str_to_title) -> df1

# create new variable 'Level' to account for overlapping records
df1 %>%
  mutate(Level = case_when(str_detect(`Floor levels t`, "Ground") ~ 1,
                                      TRUE ~ 2),
         Level = case_when(is.na(`Floor levels t`) ~ 1,
                           TRUE ~ Level)) -> df1

write_csv(df1, here("2022/data/dataframe-clean-2022.csv"))
```

```{r}
sf %>%
  select(U_ID) %>%
  left_join(df1, by = c("U_ID" = "U id")) -> sf1

st_write(sf1, here("2022/data/geoms.gpkg"), append=FALSE)
```

```{r}
sf1 %>%
  filter(Source == "WMT") %>%
  mapview()

sf1 %>%
  filter(Source == "Cities") %>%
  mapview()
```


```{r}
skim(df1) -> table
table
table %>%
  select(skim_variable, n_missing, complete_rate)
```

